require('dotenv').config();
const cron = require('node-cron');
const db = require('./lib/db'); // 🟢 使用共用 DB 模組 (解決路徑與 Table 問題)
const { getSummary } = require('./lib/ai');
const { sendDiscord, log } = require('./lib/utils');

async function runWeeklyTask() {
    log('📅', '開始執行週報任務...');

    try {
        // 1. 從資料庫撈取本週新聞
        const articles = db.getWeeklyArticles();
        
        if (articles.length === 0) {
            log('💤', '過去 7 天無新聞資料，跳過週報。');
            return;
        }

        log('📊', `本週累積新聞: ${articles.length} 則，準備進行 AI 濃縮...`);

        // 2. 為了避免 AI Token 爆炸，我們只取最近的 50-60 則代表性新聞
        // (或是你可以選擇隨機抽樣，這裡先取最新的)
        const selectedArticles = articles.slice(0, 60);

        // 3. 呼叫 AI 進行分析 (傳入 null 代表不使用增量模式，而是全新分析)
        const aiResult = await getSummary(selectedArticles, null);

        // 4. 格式化週報內容
        const weeklyReport = `
# 📅 **AI 投資週報 (Weekly Insight)**
---
**本週情緒指數**: ${aiResult.sentiment_score > 0 ? '🔥' : '❄️'} ${aiResult.sentiment_score}

## 📝 **一週重點回顧**
${aiResult.summary.replace(/<[^>]*>/g, '')} 
*(已去除 HTML 標籤以適應 Discord)*

## 🤖 **本週關鍵實體**
${aiResult.entities ? aiResult.entities.map(e => `#${e}`).join(' ') : '無'}

---
*Generated by NewsBot v2.4*
        `.trim();

        // 5. 發送
        await sendDiscord(weeklyReport);
        log('✅', '週報發送完成！');

    } catch (e) {
        log('❌', `週報執行失敗: ${e.message}`);
        console.error(e);
    }
}

// 設定排程：每週五 下午 5:00 執行 (或是你喜歡的時間)
log('🕰️', '週報機器人已就緒 (每週五 17:00)');
cron.schedule('0 17 * * 5', () => runWeeklyTask());

// 如果你想測試，可以取消下面這行的註解，重啟後會馬上跑一次
// runWeeklyTask();