require('dotenv').config();
const cron = require('node-cron');
const db = require('./lib/db');
const { getWeeklySummary } = require('./lib/ai'); // 🟢 使用新的階層式總結函式
const { sendDiscord, log } = require('./lib/utils');
const { rawKeywords } = require('./lib/config');

async function runWeeklyTask() {
    log('📅', '開始執行週報任務 (Map-Reduce 版)...');

    try {
        // 🟢 階段一：SQLite 指紋去重
        const articles = db.getWeeklyArticles();
        
        if (!articles || articles.length === 0) {
            log('💤', '本週無新聞資料，跳過。');
            return;
        }
        log('📊', `資料庫初步去重後剩餘: ${articles.length} 則`);

        // 🟢 階段二：分數權重過濾 (Keyword Weighting)
        // 針對剩下的新聞，計算關鍵字命中分數
        const scoredArticles = articles.map(article => {
            let score = 0;
            const text = (article.title + (article.content || "")).toLowerCase();
            
            // 基礎分：每中一個關鍵字 +1 分
            rawKeywords.forEach(k => {
                if (text.includes(k.toLowerCase())) score += 1;
            });

            // 加權分：標題有關鍵字額外 +2 分
            rawKeywords.forEach(k => {
                if (article.title.toLowerCase().includes(k.toLowerCase())) score += 2;
            });

            return { ...article, weight: score };
        });

        // 排序並取 Top 120 (這 120 則將進入階層式總結，分為 4 批處理)
        scoredArticles.sort((a, b) => b.weight - a.weight);
        const topArticles = scoredArticles.slice(0, 120);
        
        log('⚖️', `權重過濾後取 Top ${topArticles.length} 進行 AI 分析...`);

        // 🟢 階段三：階層式總結 (Map-Reduce)
        const aiResult = await getWeeklySummary(topArticles);

        // 4. 格式化週報
        const weeklyReport = `
# 📅 **AI 投資週報 (Weekly Insight)**
---
**本週情緒指數**: ${aiResult.sentiment_score > 0 ? '🔥' : '❄️'} ${aiResult.sentiment_score}

## 📝 **一週重點回顧**
${aiResult.summary.replace(/<[^>]*>/g, '')} 

## 🤖 **本週關鍵實體**
${aiResult.entities ? aiResult.entities.map(e => `#${e}`).join(' ') : '無'}

## 🧭 **五力分析**
- 🏛️ 政策: ${aiResult.dimensions?.policy || 0.5}
- 💰 資金: ${aiResult.dimensions?.market || 0.5}
- 🏭 產業: ${aiResult.dimensions?.industry || 0.5}
- 🌍 國際: ${aiResult.dimensions?.international || 0.5}
- 📉 技術: ${aiResult.dimensions?.technical || 0.5}

---
*Generated by NewsBot v2.6.0 (Gemini Map-Reduce)*
        `.trim();

        // 5. 發送
        await sendDiscord(weeklyReport);
        log('✅', '週報發送完成！');

    } catch (e) {
        log('❌', `週報執行失敗: ${e.message}`);
        console.error(e);
    }
}

// 設定排程：每週五 17:00
log('🕰️', '週報機器人已就緒 (每週五 17:00)');
cron.schedule('0 17 * * 5', () => runWeeklyTask());

// 測試用 (正式上線請註解)
// runWeeklyTask();