require('dotenv').config();
const cron = require('node-cron');
const db = require('./lib/db');
const { getSummary, getOpenAISummary } = require('./lib/ai');
const { openaiKey } = require('./lib/config');
const { sendDiscord, log } = require('./lib/utils');

async function runWeeklyTask() {
    log('📅', '開始執行週報任務...');

    try {
        // 1. 執行 SQLite 脫水演算法，過濾重複轉載
        const articles = db.getWeeklyArticles();
        
        if (!articles || articles.length === 0) {
            log('💤', '本週無新聞資料，跳過。');
            return;
        }

        log('📊', `原始數據約 2500 則，經演算法脫水後剩下: ${articles.length} 則精華。`);

        // 2. 限制給 AI 的最大數量（取前 100 則），確保不會超過 Token 限制
        const selectedArticles = articles.slice(0, 100);

        // 3. AI 引擎自動備援邏輯
        let aiResult;
        // 如果 .env 裡面的 OPENAI_API_KEY 是空的或沒填，會自動走 Gemini
        if (openaiKey && openaiKey.startsWith('sk-')) {
            log('🧠', '使用 OpenAI 引擎進行週報總結...');
            aiResult = await getOpenAISummary(selectedArticles);
        } else {
            log('🧠', '未偵測到有效 OpenAI Key，自動使用 Gemini 引擎備援...');
            // Gemini 模式 (傳入 null 代表全新週報分析)
            aiResult = await getSummary(selectedArticles, null);
        }

        // 4. 格式化週報
        const weeklyReport = `
# 📅 **AI 投資週報 (Weekly Insight)**
---
**本週情緒指數**: ${aiResult.sentiment_score > 0 ? '🔥' : '❄️'} ${aiResult.sentiment_score}

## 📝 **一週重點回顧**
${aiResult.summary.replace(/<[^>]*>/g, '')} 

## 🤖 **本週關鍵實體**
${aiResult.entities ? aiResult.entities.map(e => `#${e}`).join(' ') : '無'}

---
*Generated by NewsBot v2.5.2 (${openaiKey ? 'OpenAI' : 'Gemini'} Mode)*
        `.trim();

        // 5. 發送
        await sendDiscord(weeklyReport);
        log('✅', '週報任務圓滿完成！');

    } catch (e) {
        log('❌', `週報執行失敗: ${e.message}`);
        console.error(e);
    }
}

// 設定排程：每週五 17:00
log('🕰️', '週報機器人已就緒 (每週五 17:00)');
cron.schedule('0 17 * * 5', () => runWeeklyTask());

// 測試用 (正式環境請註解掉)
// runWeeklyTask();